title: Rusty Hann PowerShell
description: > # this means to ignore newlines until "baseurl:"
  PowerShell Examples by Rusty Hann.
permalink: ':title/'
baseurl: "" # the project name for GitHub Pages project sites
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: # if your site has a twitter account, enter it here

# Author Settings
author: Rusty Hann
author-img: rusty-hann.jpg
about-author: I am a Data and DevOps Eningeer focusing on PowerShell and Python.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rustyhann
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
